app_account_api:
    resource: "@KarikaPlaygroundBundle/Controller/Api/AccountController.php"
    type:   rest
    prefix:   /api

app_product_api:
    resource: "@KarikaPlaygroundBundle/Controller/Api/ProductController.php"
    type:   rest
    prefix:   /api
