<?php

namespace Karika\PlaygroundBundle\Repository;

use Karika\CoreBundle\Repository\ProductRepository as BaseProductRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends BaseProductRepository
{

    /**
     * Default ordering
     * @var array
     */
    protected $defaultOrderBy = ['id' => 'asc'];

    /**
     * @inheritdoc
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        if (!$orderBy)
        {
            $orderBy = $this->defaultOrderBy;
        }

        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

}
